name: Hello World CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello, world from mahi tech world!!"
        
      - name: Say goood bye
        run: echo "Good bye , world from mahi tech world!!"
